name: Daily Auto Commit

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Explicitly allows push[web:22]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with RANI S <22f3000632@ds.study.iitm.ac.in>
        uses: actions/checkout@v4

      - name: Create update and commit
        uses: stefanzweifel/git-auto-commit-action@v5[web:23]
        with:
          commit_message: Daily automated update by RANI S [${{ github.run_id }}]
          commit_author: RANI S <22f3000632@ds.study.iitm.ac.in>
          file_pattern: status.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
